// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdphkKSYmHw2MNss_mnonGrAIXXmh-fkU',
    appId: '1:1067095163727:web:7452daac26582a360c3b3a',
    messagingSenderId: '1067095163727',
    projectId: 'mefit-268a7',
    authDomain: 'mefit-268a7.firebaseapp.com',
    databaseURL: 'https://mefit-268a7-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mefit-268a7.firebasestorage.app',
    measurementId: 'G-0LTE24FW8Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBBGpLlnsmzl5pqpQlxRrRHWHSFrdc0Ro',
    appId: '1:1067095163727:android:9f0eaae5dd6c83800c3b3a',
    messagingSenderId: '1067095163727',
    projectId: 'mefit-268a7',
    databaseURL: 'https://mefit-268a7-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mefit-268a7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0OBLNrVxhE908-EFqGUFkx69-auUj9cY',
    appId: '1:1067095163727:ios:d5dada373cb8c88c0c3b3a',
    messagingSenderId: '1067095163727',
    projectId: 'mefit-268a7',
    databaseURL: 'https://mefit-268a7-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mefit-268a7.firebasestorage.app',
    iosBundleId: 'com.glazari.meFit',
  );
}
